FEAT : BDBD-184 휴대폰 인증 리팩토링
FakeDevelopers/BidderBidder_AOS pull request #13
Opened 2022-04-21 15:49 UTC by minseonglove

### 개요
휴대폰 인증 리팩토링

### 변경사항
* FirebaseAuth 객체를 싱글턴으로 변경했습니다
* 인증 번호 재전송 기능 추가

### 관련 지라 및 위키 링크
[BDBD-184](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-184)

### 리뷰어에게 하고 싶은 말
원래는 리팩토링만 하려했읍니다.
하지만 재전송 구현이 생각보다 쉽길레 유혹을 참지 못하고 추가했습니다.

2022-04-21 22:45 UTC, konempty requested changes
수고하셨습니다 👍 👍 안드로이드 스튜디오의 설정을 다시한번만 확인부탁드릴게요!

2022-04-21 22:45 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/di/ApiModule.kt
> +import java.util.*
ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ

2022-04-22 00:51 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/di/ApiModule.kt
> +import java.util.*
> ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ

이런!!!!!!!!!!!!!

2022-04-22 01:14 UTC, konempty approved these changes
수고하셨습니다 👍 바로 머지하셔도 좋을듯합니다!

2022-04-22 01:14 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/register/PhoneAuthFragment.kt
> +            override fun onCodeSent(p0: String, p1: PhoneAuthProvider.ForceResendingToken) {
자동생성을 해서 변수명이 이렇게 설정된것 같은데 수정하시는걸 추천드려요!

2022-04-22 01:16 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/register/PhoneAuthFragment.kt
> +            override fun onCodeSent(p0: String, p1: PhoneAuthProvider.ForceResendingToken) {
> 자동생성을 해서 변수명이 이렇게 설정된것 같은데 수정하시는걸 추천드려요!

멋진걸로 수정하고 머지하겠읍니다.

2022-04-22 01:28 UTC, merged