FEAT : BDBD-209 메인 화면 만들기
FakeDevelopers/BidderBidder_AOS pull request #28
Opened 2022-05-17 08:33 UTC by minseonglove

### 개요
메인 화면 만들기

### 변경사항
* 메인 화면 추가
  * 상단 액션바
  * 리스트 뷰
    * 받아온 상품 목록
    * 처음 리스트만 더보기 버튼으로 확장
    * 무한 스크롤
    * pull to refresh
  * 하단 네비게이션

### 관련 지라 및 위키 링크
[BDBD-209](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-209)

### 리뷰어에게 하고 싶은 말
더보기 버튼이 생각보다 만만치 않은 녀석이였어요

2022-05-17 13:25 UTC, konempty requested changes
크흐 고생하셨습니다! 조금만더 수정하면 좋을것 같아요! code smell도 수정 부탁드릴게요! ㅋㅋㅋ
![Screenshot_20220517-222417_Samsung Internet](https://user-images.githubusercontent.com/44064530/168821394-dd3be53b-2e16-4a1a-ba00-4ae50d49d517.jpg)

2022-05-17 13:25 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/util/ImageLoader.kt
> +        GlobalScope.launch(Dispatchers.IO) {
여기서 글로벌 스코프를 사용하신 이유가 무엇인지 궁금합니다!

2022-05-17 13:25 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/util/ImageLoader.kt
> +            try {
try-catch도 좋은데 코틀린스럽게 개발해보려면 runCatching써보세요!

2022-05-17 13:25 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_list/ProductListAdapter.kt
> +                            val minute = if (it > 0) "${it}분 " else ""
분단위까지만 나오니까 직관적이지 않던데 일,시간까지 추가되어야 하지않을까요?

2022-05-17 14:05 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_list/ProductListAdapter.kt
> +                            val minute = if (it > 0) "${it}분 " else ""
> 분단위까지만 나오니까 직관적이지 않던데 일,시간까지 추가되어야 하지않을까요?

지당합니다

2022-05-17 14:07 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/util/ImageLoader.kt
> +            try {
> try-catch도 좋은데 코틀린스럽게 개발해보려면 runCatching써보세요!

좋았어

2022-05-17 14:10 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/util/ImageLoader.kt
> +        GlobalScope.launch(Dispatchers.IO) {
> 여기서 글로벌 스코프를 사용하신 이유가 무엇인지 궁금합니다!

object class라 애플리케이션 라이프 싸이클을 가지므로 GlobalScope로 정의를 했는데 좀 더 멋진 방법을 고민해 볼게요

2022-05-18 13:30 UTC, konempty approved these changes
크흐 고생하셨습니다! 제가 달아둔 리뷰에 대해 전부 타당한 이유가 있어서 적용되지 않아도 되겠다 싶으시면 바로 머지 하셔도 좋습니다! 단, 수정을 조금이라도 하면 다시 리뷰요청 주세요! :)

2022-05-18 13:30 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/util/ImageLoader.kt
> +        if (imageCache.containsKey(url)) {
이미지 캐시가 너무 커지면 메모리 부족을 일으킬수 있고 앱을 꺼지면 휘발된다는 단점이 있네요! 이를 위해 보통 캐시 "파일"을 사용합니다 한번 그걸 적용해보시면 좋을것 같아요!

2022-05-18 13:30 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_list/ProductListAdapter.kt
> +                CoroutineScope(Dispatchers.IO).launch {
호오 Dispatcher에는 main, io, default 이 3개가 있는데 이 상황에선 어떤게 가장 옳은 선택일까요?ㅋㅋㅋㅋ 본인의 생각을 표현해주세요!

2022-05-18 13:30 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_list/ProductListAdapter.kt
> +                            imageProductList.setImageBitmap(it)
흐음 잘못하면 두개 이상의 코루틴이 한개의 이미지뷰에 접근하게 될수있지않을까요? 제가 보기엔 병렬작업의 동기화를 맞춰주는  코드가 추가되어야 할것 같은데 이부분 확인 부탁드릴게요! 문제없다면 넘어가셔도 좋습니다!

2022-05-18 13:35 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_list/ProductListAdapter.kt
> +                CoroutineScope(Dispatchers.IO).launch {
> 호오 Dispatcher에는 main, io, default 이 3개가 있는데 이 상황에선 어떤게 가장 옳은 선택일까요?ㅋㅋㅋㅋ 본인의 생각을 표현해주세요!

loadProductImage는 url을 가지고 이미지를 요청하는 메소드 입니다 네트워크 작업이기 때문에 Dispatchers IO로 감쌌읍니다.
loadProductImage의 인자로 넣은 콜백 메소드는 UI를 변경하는 메소드기 때문에 loadProductImage 메소드 안에서 Dispatcher Main으로 따로 감싸줬습니다.

2022-05-18 13:40 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/util/ImageLoader.kt
> +        if (imageCache.containsKey(url)) {
> 이미지 캐시가 너무 커지면 메모리 부족을 일으킬수 있고 앱을 꺼지면 휘발된다는 단점이 있네요! 이를 위해 보통 캐시 "파일"을 사용합니다 한번 그걸 적용해보시면 좋을것 같아요!

앱이 꺼지면 캐시도 사라지는건 의도한 부분이긴 한데 메모리 문제는 지나칠 수가 없군요

2022-05-18 13:43 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_list/ProductListAdapter.kt
> +                            imageProductList.setImageBitmap(it)
> 흐음 잘못하면 두개 이상의 코루틴이 한개의 이미지뷰에 접근하게 될수있지않을까요? 제가 보기엔 병렬작업의 동기화를 맞춰주는 코드가 추가되어야 할것 같은데 이부분 확인 부탁드릴게요! 문제없다면 넘어가셔도 좋습니다!

안드로이드의 UI 작업은 메세지 풀에서 하나씩 때와서 처리가 되기 때문에 동기화 문제는 없다고 뵙니다

2022-05-18 15:20 UTC, konempty approved these changes
크흐 고생하셨습니다!

2022-05-18 15:20 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_list/ProductListAdapter.kt
> +                    .error(R.drawable.the_cat)
👍

2022-05-19 00:58 UTC, merged