FEAT : BDBD-390 홈 버튼 터치 기능 추가
FakeDevelopers/BidderBidder_AOS pull request #53
Opened 2022-07-22 13:40 UTC by re4rk

### 개요
 - 하단 네비게이션 기능 개발
### 변경사항
 - 홈 버튼 터치 기능 추가
   - 홈 버튼 터치시 최신화
   - 스크롤 최상단으로 이동
   - 더보기 버튼 재 생성
   - 기존 검색어 초기화
 - 홈 버튼으로 검색어 초기화 시 버그 발생 수정
### 관련 지라 및 위키 링크
  - [BDBD-390](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-390&text=390)
### 리뷰어에게 하고 싶은 말
  - 404 Not Found

2022-07-22 13:58 UTC, minseonglove requested changes
코틀린 문법도 벌써 익히고 대단한데
요것만 수정해줘

2022-07-22 13:58 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/MainActivity.kt
> +                    view.performClick()
view.performClick()를 ACTION_UP으로 옮기면 when으로 분기를 나눌 필요가 없어져서 되게 깔끔해질테야

2022-07-22 13:58 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/MainActivity.kt
> +                view: View, motionEvent: MotionEvent ->
이건 스타일이긴한데
프로젝트에서 람다를 쓸 땐 매개변수 타입을 안넣고 쓰고 있어서 여기도 빼는게 이쁠 것 같다

2022-07-22 14:28 UTC, minseonglove approved these changes
![yQoeObI](https://user-images.githubusercontent.com/90435036/180460935-c37d2508-86cb-4200-a9bb-2921ae2512d6.gif)
아름답지않니

2022-07-26 00:48 UTC, minseonglove approved these changes
https://luv-n-interest.tistory.com/461
야 처럼 navigate 중 인걸 알 수 있는 공유 변수를 하나 둘랑가 했었는데
이것도 방법이겠구나

2022-07-26 00:48 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/MainActivity.kt
> +                    }
runCatching을 사용하면 좀 더 간지나게 예외처리를 할 수 있어

2022-07-26 00:51 UTC, minseonglove approved these changes

2022-07-26 00:51 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/MainActivity.kt
> +                    }
하단 네비게이션으로 navigate하는 동작은 모두 같은 문제를 가지고 있을테니까
navigate 부분은 따로 함수를 만들어서 처리해주는 것도 좋겠구나

2022-07-26 01:26 UTC, minseonglove approved these changes

2022-07-26 01:26 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/MainActivity.kt
> +        val changeBottomNavigation = fun(navDirections: NavDirections) {
왜 변수로 할당했는지 알 수 있을까

2022-07-26 04:27 UTC, re4rk commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/MainActivity.kt
> +        val changeBottomNavigation = fun(navDirections: NavDirections) {
익명 함수 사용법이라서 썻는데 이것보다는 Wrap 방식이 더 어울릴 것강ㅌ네요 ㅋㅋ

2022-07-26 04:28 UTC, re4rk commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/MainActivity.kt
> +        val changeBottomNavigation = fun(navDirections: NavDirections) {
수정했습니다!

2022-07-27 12:27 UTC, konempty approved these changes
고생하셨습니다 👍

2022-07-27 12:29 UTC, merged