FEAT : BDBD-398 구글 소셜 로그인 기능 추가
FakeDevelopers/BidderBidder_AOS pull request #56
Opened 2022-07-26 16:12 UTC by re4rk

### 개요
 - 구글 소셜 로그인 기능 추가
### 변경사항
 - nav_graph 추가
 - LoginTypeFagment에 구글 로그인 구현
### 관련 지라 및 위키 링크
 - [BDBD-398](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-398)
### 리뷰어에게 하고 싶은 말
 - 404 Not Found

2022-07-27 13:28 UTC, konempty requested changes
고생하셨습니다 👍 조금만더 수정 부탁드릴게요!ㅎㅎ

2022-07-27 13:28 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
변수명을 축약해서 쓰면 작성한 당사자는 이해하기 쉽지만 다른사람에게는 이해가 안될수도 있어요 축약형은 지양해주세요 ㅎㅎ

2022-07-27 13:28 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +            val result = Auth.GoogleSignInApi.getSignInResultFromIntent(result.data!!)
헛.. result라는 이름이 중복되었네요 함수의 파라메터와 내부 변수의 이름을 다르게 해주시면 좋을것 같아요!

2022-07-27 13:28 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +            if (result!!.isSuccess) {
result가 null이 아닌게 확실한거죠?

2022-07-27 15:09 UTC, minseonglove approved these changes
우선 !!는 지양해야해 null 값에 !!를 쓰면 바로 앱이 터지기 때문이야
그래서 어지간하면 !! 대신 null check 방법을 익혀서 사용하는걸 추천해

현재 많은 동작이 Fragment안에 박혀있는데 액티비티를 받아야하는 googleSignInClient를 제외하고 ViewModel 클래스를 만들어서 거기로 빼는게 좋아보인다.
어떤식으로 해야할지 애매하다면 할일 바구니에 동작을 정리해줄게

2022-07-27 15:09 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +    val requestActivity = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
private으로 선언하고 얘도 변수니까 위에 변수랑 같이 있는게 이쁠거야

2022-07-27 15:09 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +    fun firebaseAuthWithGoogle(account: GoogleSignInAccount?) {
이 역시 private

2022-07-27 15:09 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +                firebaseAuthWithGoogle(account)
여기서 account에 대한 null 검사를 수행한다면 firebaseAuthWithGoogle이 non-null한 매개변수를 받을 수 있어

2022-07-31 07:37 UTC, minseonglove requested changes
UI와 관계 없는 작업들을 ViewModel로 빼버리니까 아름답지 않니
쪼금만 수정해줘

2022-07-31 07:37 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/SigninGoogleDto.kt
> +    val email: Long,
어어

2022-07-31 07:37 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeViewModel.kt
> +                    signinGoogleRequest()
Bearer는 인증할 때 많이 붙여쓸거 같으니까
상수로 빼는것도 좋겠다

2022-07-31 07:37 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/di/ApiModule.kt
> +class NullOnEmptyConverterFactory : Converter.Factory() {
이건 무슨 역할을 하니

2022-07-31 07:37 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/di/ApiModule.kt
> +    fun provideSiginGoogleRepository(service: SigninGoogleService): SiginGoogleRepository =
앗 오타

2022-07-31 07:37 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +                        Toast.makeText(requireActivity(), "success", Toast.LENGTH_LONG).show()
나중엔 여기에 DataStore로 토큰을 저장하는 부분이 추가돼야겠지
이건 지금 말고 따로 작업을 파서 해도 돼

2022-07-31 07:37 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +        viewModel.firebaseAuth = FirebaseAuth.getInstance()
FirebaseAuth도 repository 처럼 생성자 주입으로 사용할 수 있게 해놨어
PhoneAuthViewModel을 보면 사용예시를 볼 수 있어

2022-07-31 07:37 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +                }
```
result.signInAccount?.let { account ->
    viewModel.firebaseAuthWithGoogle(account)
}
```
?.let으로 null 검사를 수행하면 좀 더 이쁘게 짤 수 있어

2022-07-31 07:37 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeViewModel.kt
> +    var token: String = ""
private..!

2022-07-31 07:37 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeViewModel.kt
> +            _signinGoogleResponse.emit(repository.postSigninGoogle(token))
좋아

2022-07-31 07:37 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +        requestActivity.launch(signInIntent)
구글로그인을 메소드로 분리한건 좋은 선택이야
이건 스타일 문제긴 한데 난 보통 변수 선언이 길지 않다면 변수를 따로 선언 하지 않고
`requestActivity.launch(googleSignInClient.signInIntent)`
이렇게 한 줄로 치워버리는 스타일이야

2022-07-31 07:39 UTC, re4rk commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/di/ApiModule.kt
> +class NullOnEmptyConverterFactory : Converter.Factory() {
서버에서 200ok 인데 email이랑 nickname 안줘서  로그인 못 하는 것때문에 임시로 반환값없어도 200ok면 통과시키게 만드는 클래스입니당

2022-08-02 09:27 UTC, minseonglove requested changes
좋아좋아 거의 다 왔어

2022-08-02 09:27 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/datastore/DatastoreSetting.kt
> +        private const val TOKEN_HISTORY_KEY = "token_history"
ㅋㅋ search_history는 진짜 검색기록이라서 history를 붙인거야
적당한 이름으로 바꿔줘

2022-08-02 09:27 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/di/ApiModule.kt
> +import java.util.*
와일드 임포트..!

2022-08-02 09:27 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +                            preferences[TOKEN_HISTORY] = viewModel.token.value
굿

2022-08-02 09:27 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +                        viewModel.signinGoogleRequestWithDataStoreToken(it)
이 부분은 없어도 된다고 봐
로그인 타입 화면은 처음 방문 or 로그아웃한 유저가 들어올거란 말이여
처음온 사람이라면 당연히 토큰이 없을테고
로그아웃으로온 사람이라면 다른 소셜 계정으로 로그인 하고싶은 사람들도 있기 때문에 새 토큰을 발급 하는게 맞아

지금과 같이 토큰이 있나 확인하는 작업은 앱을 가동했을 때 나오는 로딩 화면(지금은 없음 ㅎ)에서 수행하는게 맞겠지

2022-08-02 09:27 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeViewModel.kt
> +    private val bearer = "Bearer "
요런건 상수로 빼는게 간지야 
Bearer는 소셜 로그인 뿐만 아니라 토큰을 검증해야 하는 모든 작업에 쓰여야 하니까
LoginTypeViewModel 보다는 어디에 Object Class 하나 만들어서 거기 안에 정의하는게 좋겠다.

2022-08-02 09:27 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeViewModel.kt
> +    private val _auth: FirebaseAuth
굿

2022-08-02 09:27 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeViewModel.kt
> +    val auth get() = _auth
이건 필요 없어 보이네

2022-08-05 17:16 UTC, minseonglove requested changes
리뷰 요청한걸 지금 봤네 
내가 미리 알려줬어야 했는데 리뷰 재요청을 하면 한번은 까톡으로 호출해줘

2022-08-05 17:16 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +        googleSignInClient = GoogleSignIn.getClient(requireActivity(), googleSignInOptions)
```
val googleSignInOptions = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
  .requestIdToken(WEB_CLIENT_ID)
  .requestEmail()
  .build()
googleSignInClient = GoogleSignIn.getClient(requireActivity(), googleSignInOptions)
```
이 부분 googleLogin() 안으로 옮겨줘
원인은 더 알아봐야겠지만 이게 Create에서 초기화 될 때 회원가입 휴대폰 인증 콜백을 백그라운드에서 못 받는 버그가 생겨

2022-08-05 17:16 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/login_type/LoginTypeFragment.kt
> +        requireContext().datastore.data
BEARER_TOKEN_PREFIX 상수만 남겨두고
DataStore를 사용하는 부분은 모두 제거해줘 파이어베이스 토큰을 저장하는건 의미가 없데

2022-08-13 04:23 UTC, konempty approved these changes
고생하셨습니다 👍

2022-08-13 05:30 UTC, minseonglove approved these changes
좋아
nav_graph 에서 컨플릭트가 나와서 머지를 못할텐데
컨플릭트 수정할 때 develop의 nav_graph 내용을 그대로 가져와서 덮어씌우면돼

2022-08-13 06:26 UTC, merged