FEAT : BDBD-433 상품 등록 카테고리 api 연동
FakeDevelopers/BidderBidder_AOS pull request #69
Opened 2022-09-23 14:39 UTC by re4rk

### 개요
* 상품 등록 카테고리 api 연동

### 변경사항
*  관련 repository, service 추가 
*  물품 등록 요청 시 선택한 카테고리에 해당하는 ID 전달

### 관련 지라 및 위키 링크
* [BDBD-433](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-433)

### 리뷰어에게 하고 싶은 말
* viewModel에 카테고리를 저장하고 있는데 재생성 마다 되고 있습니다. 서버가 멀리 있기에 카테고리가 늦게 뜨는 것이 더 체감 되네요..

2022-09-23 14:56 UTC, konempty approved these changes
고생 하셨습니다! 👍 코드 스멜이랑 컨플릭도 수정 주탁드릴게요!

2022-09-23 14:56 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationFragment.kt
> +            viewModel.productCategory.collectLatest {
collectLastest를 쓰신이유가 무엇일까요?

2022-09-23 14:56 UTC, konempty commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationViewModel.kt
> +            category.add(it.categoryName)
lost 내용의 카피가 아니라 category=list 이런식으로 대입도 가능하지 않았을까요?

2022-09-23 15:03 UTC, minseonglove requested changes
작업을 할 때마다 강해지는게 느껴지는구나
다른건 categoryID와 error 받는 부분만 수정해줘

2022-09-23 15:03 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationViewModel.kt
> +    fun productCategoryRequest() {
함수의 시작은 동사로 해야해
라고 할라 했는데 내가 먼저 게시글 등록 함수를 이런식으로 썼었구나

2022-09-23 15:03 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationViewModel.kt
> +                    Logger.e(it.errorBody().toString())
ApiErrorHandler의 print를 사용해줘

2022-09-23 15:03 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationViewModel.kt
> +                    _productCategory.emit(it.body()!!)
어썰트는 좋지 못해
라고 할라 했는데 내가 상품 리스트 가져오는 api도 이런식으로 했구만

2022-09-23 15:03 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationViewModel.kt
> +    val categoryID: MutableStateFlow<Long> = MutableStateFlow(0)
데이터 바인딩을 하거나 Collector를 등록하는게 아니라면 StateFlow는 무의미 한 것이야

2022-09-23 15:03 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationFragment.kt
> +    private fun setCategory(category: List<String>) {
함수로 뺐군 이쁘네

2022-09-23 15:03 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationViewModel.kt
> +        list.forEach() {
forEach는 괄호를 생략해서 쓸 수 있어
얘는 map을 활용하거나 아예 var로 선언해서 대입을 하면 더 깔끔하게 넣어지겠다

2022-09-23 15:03 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationFragment.kt
> +                }
정의 하지 않는 메소드는 주석을 달아놔야 소나가 잔소리 안하드라

2022-09-24 03:38 UTC, re4rk commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationFragment.kt
> +            viewModel.productCategory.collectLatest {
제가 collectlatest를 사용한 이유는 가장 최신 것을 가져오기 때문이였는데 어차피 카테고리는 view가 생성될 때 한번만 설정되는 collect를 사용해도 된다는 말씀으로 이해했는데 맞을까요??

2022-09-24 04:00 UTC, konempty approved these changes
고생하셨습니다 👍 톡으로 말씀드린것만 수정해주시면 저는 승인합니다!ㅋㅋㅋ

2022-09-24 06:11 UTC, minseonglove approved these changes
![yQoeObI](https://user-images.githubusercontent.com/90435036/192082880-8ee9e0e4-a1fc-491d-a3ae-ecc3f772d34b.gif)

좋았어
category 접근자만 바꿔주면 통과해도돼

글쓰기 때 마다 카테고리를 받아오는건 힘드니까 앱을 켤 때 한 번만 받아오는 방식도 고려해볼 필요가 있겠군

2022-09-24 06:11 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationViewModel.kt
> +    var category: List<String> = listOf()
가변 변수를 public으로 하는것은 좋지 않아
private set을 활용하면 내부에서만 변경 가능하게 만들 수 있어

2022-09-24 06:11 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationViewModel.kt
> +                    it.body()?.let { it1 -> _productCategory.emit(it1) }
it이 중첩되는 상황에서는 변수명으로 it1, it2 보단 들어오는 변수가 정확히 뭔지 알 수 있는 이름으로 하는게 이쁠테야

2022-09-24 06:11 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationFragment.kt
> +            viewModel.productCategory.collect {
collect와 collectLastest의 차이가 무엇인지 알고있니

2022-09-24 06:16 UTC, re4rk commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationFragment.kt
> +            viewModel.productCategory.collect {
여러번 찾아보았고 지금은 collect는 들어온 순서대로 모두 처리하고 collectlastest는 여러개가 처리전에 들어오면 마지막 곳만 처리한다고 이해하고 있습니다!

2022-09-24 06:24 UTC, minseonglove commented on app/src/main/kotlin/com/fakedevelopers/bidderbidder/ui/product_registration/ProductRegistrationFragment.kt
> +            viewModel.productCategory.collect {
> 여러번 찾아보았고 지금은 collect는 들어온 순서대로 모두 처리하고 collectlastest는 여러개가 처리전에 들어오면 마지막 곳만 처리한다고 이해하고 있습니다!

좋아 꼼꼼히 다 알아봤었구나
이건 스타일 차이일수도 있지만 난 무조건 collectLastest를 기본으로 쓴 다음 순차 처리가 필요한것만 collect로 바꾸는 편이야

2022-09-27 13:34 UTC, merged